export type Product={slug:string;name:string;category:string;collection:string;finish:string;description:string;price:number;perInch:number;sizes:number[];shape:string;model?:string;featured?:boolean;newArrival?:boolean;bestSeller?:boolean};
export type Collection={slug:string;number:string;name:string;short:string;description:string;shape:string};
export const collections:Collection[]=[
{slug:"divine-forms",number:"01",name:"Divine Forms",short:"Sacred sculptures with quiet presence.",description:"Devotional forms created to bring stillness, character and a sense of ritual into considered spaces.",shape:"form-divine"},
{slug:"buddha",number:"02",name:"Buddha",short:"Stillness, balance and contemplative form.",description:"Meditative sculptures inspired by calm, proportion and timeless presence.",shape:"form-buddha"},
{slug:"modern-art",number:"03",name:"Modern Art",short:"Sculptural pieces for contemporary spaces.",description:"Abstract and architectural forms for interiors that speak in a quieter visual language.",shape:"form-modern"},
{slug:"home-decor",number:"04",name:"Home Décor",short:"Objects designed to become focal points.",description:"Decorative objects with sculptural character, designed for shelves, consoles and living spaces.",shape:"form-decor"}];
export const products:Product[]=[
{slug:"the-meditative-one",name:"The Meditative One",category:"Buddha",collection:"buddha",finish:"Stone Finish",description:"A balanced seated form designed around stillness and quiet symmetry. Its restrained stone finish gives it a timeless gallery presence.",price:2850,perInch:150,sizes:[3,4,5,6,7,8,9,10,11,12],shape:"figure-a",featured:true,bestSeller:true},
{slug:"eternal-gaze",name:"Eternal Gaze",category:"Devotional",collection:"divine-forms",finish:"Antique Finish",description:"A devotional portrait with softened edges and an antique surface that rewards close inspection.",price:3450,perInch:175,sizes:[4,5,6,7,8,9,10,11,12],shape:"figure-b",featured:true,newArrival:true},
{slug:"the-union",name:"The Union",category:"Couple Sculpture",collection:"divine-forms",finish:"Ivory Finish",description:"Two forms meeting as one continuous silhouette. Made as a statement of companionship and balance.",price:2950,perInch:160,sizes:[4,5,6,7,8,9,10,11,12],shape:"figure-c",featured:true},
{slug:"arc-of-silence",name:"Arc of Silence",category:"Modern Art",collection:"modern-art",finish:"Bronze Finish",description:"An architectural gesture captured in sculptural form, made to create a strong focal point without visual noise.",price:4200,perInch:220,sizes:[5,6,7,8,9,10,11,12],shape:"figure-d",featured:true},
{slug:"temple-form",name:"Temple Form",category:"Decorative",collection:"home-decor",finish:"Sandstone Finish",description:"A compact decorative form with a tactile sandstone character, designed for consoles and intimate spaces.",price:2250,perInch:125,sizes:[3,4,5,6,7,8,9,10],shape:"figure-e",featured:true,newArrival:true},
{slug:"the-guardian",name:"The Guardian",category:"Devotional",collection:"divine-forms",finish:"Charcoal Finish",description:"A grounded guardian silhouette with a deep charcoal finish and a quiet, ceremonial character.",price:3900,perInch:200,sizes:[5,6,7,8,9,10,11,12],shape:"figure-f",featured:true,bestSeller:true},
{slug:"quiet-lotus",name:"Quiet Lotus",category:"Buddha",collection:"buddha",finish:"Warm Stone",description:"A contemplative lotus-inspired form with soft geometry and an understated finish.",price:2650,perInch:140,sizes:[3,4,5,6,7,8,9,10],shape:"figure-a",newArrival:true},
{slug:"monolith-i",name:"Monolith I",category:"Modern Art",collection:"modern-art",finish:"Graphite",description:"A tall, minimal sculptural study for contemporary rooms and architectural interiors.",price:4800,perInch:240,sizes:[6,7,8,9,10,11,12],shape:"figure-d"},
{slug:"the-observer",name:"The Observer",category:"Home Décor",collection:"home-decor",finish:"Travertine",description:"A small-scale sculptural object with a strong silhouette and natural stone character.",price:2100,perInch:120,sizes:[3,4,5,6,7,8,9],shape:"figure-e",bestSeller:true},
{slug:"sacred-profile",name:"Sacred Profile",category:"Devotional",collection:"divine-forms",finish:"Ivory Stone",description:"A refined profile study designed to sit comfortably within both traditional and contemporary interiors.",price:3100,perInch:155,sizes:[4,5,6,7,8,9,10,11],shape:"figure-b",newArrival:true},
{slug:"balance-study",name:"Balance Study",category:"Modern Art",collection:"modern-art",finish:"Aged Bronze",description:"Interlocking volumes create a sense of movement while maintaining a grounded, gallery-like silhouette.",price:4400,perInch:225,sizes:[5,6,7,8,9,10,11,12],shape:"figure-c"},
{slug:"ritual-vessel",name:"Ritual Vessel",category:"Home Décor",collection:"home-decor",finish:"Stone Grey",description:"A sculptural vessel where useful object and decorative form become one.",price:2350,perInch:130,sizes:[3,4,5,6,7,8,9,10],shape:"figure-e"}];
export const money=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v);
export const priceForSize=(p:Product,s:number)=>p.price+Math.max(0,s-p.sizes[0])*p.perInch;
export const getCollection=(slug:string)=>collections.find(x=>x.slug===slug);
export const getProduct=(slug:string)=>products.find(x=>x.slug===slug);